apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:1.14
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: VAR
            value: '${{URL}}'
        imagePullPolicy: Always
restartPolicy: Always
